<?php

namespace App\Repository;

use App\Entity\ClientAccountBillingEntity;

/**
 * ClientAccountBillingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientAccountBillingRepository extends \Doctrine\ORM\EntityRepository
{

    public function validate($clientAccountBilling_form, $clientAccount) {

        $errors = array();

        $action = $clientAccountBilling_form['action'];

        $billingDate = $clientAccountBilling_form['billingDate'];

        // d = delete
        if($action !== 'd') {
            $clientAccountBillingExist = $this->getEntityManager()->getRepository(ClientAccountBillingEntity::class)
                ->createQueryBuilder('cmr')
                ->where('cmr.id !=  :id')
                ->andWhere('cmr.isDeleted =  0')
                ->andWhere('cmr.clientAccount = :clientAccountId')
                ->andWhere('cmr.billingDate BETWEEN :startDate AND :endDate')
                ->setParameters(array(
                    'clientAccountId' => base64_decode($clientAccountBilling_form['clientAccount']),
                    'startDate' => date("Y-m-01",strtotime($clientAccountBilling_form['billingDate'])) . ' 00:00:00',
                    'endDate' => date("Y-m-t",strtotime($clientAccountBilling_form['billingDate'])) . ' 23:59:59',
                    'id' => $clientAccountBilling_form['id']
                ))
                ->getQuery()->getResult();

            if($clientAccountBillingExist) {
                $errors[] = 'Account already has a billing this month.';
            }

            if(strtotime($clientAccount->getLastBillingDateAsString()) > strtotime($clientAccountBilling_form['billingDate'])){
                $errors[] = 'Invalid  billing date.';

            }

            
        }

        return $errors;
    }

    public function ajax_list(array $get, $userData){

        $columns = array(
            array('cmr.`id`', "cmr.`id`"),
            array('DATE_FORMAT(cmr.`billing_date`,"%m/%d/%Y")', 'DATE_FORMAT(cmr.`billing_date`,"%m/%d/%Y")', 'billingDate'),
            array('cmr.`status`', 'cmr.`status`', 'status'),
            array('cmr.`billed_amount`', 'cmr.`billed_amount`', 'billedAmount'),
            array('DATE_FORMAT(cmr.`due_date`,"%m/%d/%Y")','DATE_FORMAT(cmr.`due_date`,"%m/%d/%Y")', 'dueDate'),
        );
        $asColumns = array();

        $select = "SELECT";
        $from = "FROM `client_account_billing` cmr";
        $sqlWhere = " WHERE cmr.`is_deleted` = 0";
        $joins = "";
        $groupBy = "";
        $orderBy = "";
        $limit = "";
        $stmtParams = array();

        foreach($columns as $key => $column) {
            $select .= ($key > 0 ? ', ' : ' ') . $column[1] . (isset($column[2]) ? ' AS ' . $column[2] : '');
        }


        if($userData['type'] != 'Super Admin' || $get['clientAccountId']){

            $sqlWhere .= " AND cmr.`client_account_id` = :clientAccountId";
            $stmtParams['clientAccountId'] = base64_decode($get['clientAccountId']);
        }

        /*
         * Ordering
         */
        foreach($get['columns'] as $key => $column) {
            if($column['orderable']=='true') {
                if(isSet($get['order'])) {
                    foreach($get['order'] as $order) {
                        if($order['column']==$key) {
                            $orderBy .= (!empty($orderBy) ? ', ' : 'ORDER BY ') . $columns[$key][0] . (!empty($order['dir']) ? ' ' . $order['dir'] : '');
                        }
                    }
                }
            }
        }

        /*
         * Filtering
         */
        if(isset($get['search']) && $get['search']['value'] != ''){
            $aLikes = array();
            foreach($get['columns'] as $key => $column) {
                if($column['searchable']=='true') {
                    $aLikes[] = $columns[$key][0] . ' LIKE :searchValue';
                }
            }
            foreach($asColumns as $asColumn) {
                $aLikes[] = $asColumn . ' LIKE :searchValue';
            }
            if(count($aLikes)) {
                $sqlWhere .= (!empty($sqlWhere) ? ' AND ' : 'WHERE ') . '(' . implode(' OR ', $aLikes) . ')';
                $stmtParams['searchValue'] = "%" . $get['search']['value'] . "%";
            }
        }

        /* Set Limit and Length */
        if(isset( $get['start'] ) && $get['length'] != '-1'){
            $limit = 'LIMIT ' . (int)$get['start'] . ',' . (int)$get['length'];
        }

        $sql = "$select $from $joins $sqlWhere $groupBy $orderBy";
        $query = $this->getEntityManager()->getConnection()->prepare($sql);
     

        foreach($stmtParams as $k => $v){
            $query->bindValue($k, $v);

        }
        $res = $query->executeQuery();
        $result_count = $res->fetchAllAssociative();
        $sql = "$select $from $joins $sqlWhere $groupBy $orderBy $limit";
        $query = $this->getEntityManager()->getConnection()->prepare($sql);
        foreach($stmtParams as $k => $v){
            $query->bindValue($k, $v);

        }
        $res = $query->executeQuery();
        $result = $res->fetchAllAssociative();

        /* Data Count */
        $recordsTotal = count($result_count);

        /*
         * Output
         */
        $output = array(
            "draw" => intval($get['draw']),
            "recordsTotal" => $recordsTotal,
            "recordsFiltered" => $recordsTotal,
            "data" => array()
        );

        $url = $get['url'];
        $formUrl = '';
        $printUrl = 'client_account/print/temporary_receipt/';
        $hasUpdate = false;
        $hasPrint = false;
        $hasDetails = false;

        
        if($userData['type'] == 'Super Admin'  || in_array('Client Details Account Details Billing Update', $userData['accesses'])){
            $hasUpdate = true;
        }

        if($userData['type'] == 'Super Admin'  || in_array('Client Details Account Details Billing Print', $userData['accesses'])){
            $hasPrint = true;
        }

        $action = '';


        foreach($result as $k => $row) {
            $id = base64_encode($row['id']);
         
            $action .= $hasUpdate ? "<a class='action-button-style btn btn-primary  href-modal' href='javascript:void(0)' data-id='".$id."' data-action='u' data-type='billing'>Update</a>" : "";
            $action .= $hasPrint ? " <a class='action-button-style btn btn-primary'  href='".$url.$printUrl.$id."' target='_blank'>Download</a>" : "";
            $values = array(
                $row['billingDate'],
                $row['status'],
                $row['billedAmount'],
                $row['dueDate'],
                $k === array_key_first($result) ? $action : ''
                
            );

            $output['data'][] = $values;
        }

        unset($result);

        return $output;
    }

    public function autocompleteSuggestions($q, $userData) {

        $stmtParams = array(
            'q' => "%" . $q['query'] . "%"
        );
        $andWhere = '';

        if($userData['type'] != 'Super Admin'){

             $andWhere.= ' WHERE u.branch_id = :branchId'; 
             $stmtParams['branchId'] = $userData['branchId'];   
        }

        
        $query = $this->getEntityManager()->getConnection()->prepare("
            SELECT
                u.`id`,
                CONCAT(u.`first_name`, ' ', u.`last_name`) AS data,
                CONCAT(u.`first_name`, ' ', u.`last_name`) AS value
            FROM `client` u
            $andWhere
            AND u.`is_deleted` != 1
            AND CONCAT(u.`first_name`, ' ', u.`last_name`) LIKE :q
            ORDER BY u.`first_name`
            LIMIT 0,20
        ");

        foreach($stmtParams as $k => $v){
            $query->bindValue($k, $v);

        }
       
        $res = $query->executeQuery();
        $result = $res->fetchAllAssociative();
        return $result;
    }

   public function consumption_ajax_list($get, $userData){
        
        $columns = array(
            array('CONCAT(c.`first_name`, " ", c.`last_name`, " - ", cm.`account_serial_no`)', 'CONCAT(c.`first_name`, " ", c.`last_name`, " - ", cm.`account_serial_no`)', "account"),
            array('p.`description`', 'p.`description`', 'purok'),
            array('cmr.`billed_amount`', 'cmr.`billed_amount`', 'billedAmount'),

            array('cmr.`consume`', 'cmr.`consume`', 'consume'),
        );

        $asColumns = array();

        $select = "SELECT";
        $from = "FROM `client_account_billing` cmr";
        $sqlWhere = " WHERE cmr.`is_deleted` = 0";
        $joins = " LEFT JOIN `client_account` cm ON cm.`id` = cmr.`client_account_id`";
        $joins .= " LEFT JOIN `client` c ON c.`id` = cm.`client_id`";
        $joins .= " LEFT JOIN `purok` p ON p.`id` = cm.`purok_id`";

        $groupBy = "";
        $orderBy = "";
        $limit = "";
        $stmtParams = array();

        foreach($columns as $key => $column) {
            $select .= ($key > 0 ? ', ' : ' ') . $column[1] . (isset($column[2]) ? ' AS ' . $column[2] : '');
        }

        if($userData['type'] != 'Super Admin'){

            $sqlWhere.= ' AND c.branch_id = :branchId'; 
            $stmtParams['branchId'] = base64_decode($userData['branchId']);   
       }

        if($get['date']){
            $sqlWhere.= ' AND cmr.`billing_date` BETWEEN "' .date("Y-m-01",strtotime($get['date'])) . ' 00:00:00" AND "'.date("Y-m-t",strtotime($get['date'])) . ' 23:59:59"';    
        }

        if($get['purok'] && $get['purok'] != 'All' ){
            $sqlWhere.= ' AND p.`id` =:purok';
            $stmtParams['purok'] = base64_decode($get['purok']);   

        }

        /*
        * Ordering
        */
        foreach($get['columns'] as $key => $column) {
            if($column['orderable']=='true') {
                if(isSet($get['order'])) {
                    foreach($get['order'] as $order) {
                        if($order['column']==$key) {
                            $orderBy .= (!empty($orderBy) ? ', ' : 'ORDER BY ') . $columns[$key][0] . (!empty($order['dir']) ? ' ' . $order['dir'] : '');
                        }
                    }
                }
            }
        }

        /*
        * Filtering
        */
        if(isset($get['search']) && $get['search']['value'] != ''){
            $aLikes = array();
            foreach($get['columns'] as $key => $column) {
                if($column['searchable']=='true') {
                    $aLikes[] = $columns[$key][0] . ' LIKE :searchValue';
                }
            }
            foreach($asColumns as $asColumn) {
                $aLikes[] = $asColumn . ' LIKE :searchValue';
            }
            if(count($aLikes)) {
                $sqlWhere .= (!empty($sqlWhere) ? ' AND ' : 'WHERE ') . '(' . implode(' OR ', $aLikes) . ')';
                $stmtParams['searchValue'] = "%" . $get['search']['value'] . "%";
            }
        }

        /* Set Limit and Length */
        if(isset( $get['start'] ) && $get['length'] != '-1'){
            $limit = 'LIMIT ' . (int)$get['start'] . ',' . (int)$get['length'];
        }

        $sql = "$select $from $joins $sqlWhere $groupBy $orderBy";

        $query = $this->getEntityManager()->getConnection()->prepare($sql);
    

        foreach($stmtParams as $k => $v){
            $query->bindValue($k, $v);

        }
        $res = $query->executeQuery();
        $result_count = $res->fetchAllAssociative();
        $sql = "$select $from $joins $sqlWhere $groupBy $orderBy $limit";
        $query = $this->getEntityManager()->getConnection()->prepare($sql);
        foreach($stmtParams as $k => $v){
            $query->bindValue($k, $v);

        }
        $res = $query->executeQuery();
        $result = $res->fetchAllAssociative();

        /* Data Count */
        $recordsTotal = count($result_count);

        /*
        * Output
        */
        $output = array(
            "draw" => intval($get['draw']),
            "recordsTotal" => $recordsTotal,
            "recordsFiltered" => $recordsTotal,
            "data" => array()
        );


        foreach($result as $k => $row) {
            $values = array(
                $row['account'],
                $row['purok'],
                $row['billedAmount'],

                $row['consume'],
                
            );

            $output['data'][] = $values;
        }

        unset($result);

        return $output;
   }

   public function consumptionData($date, $purok, $userData){
   

        $stmtParams = array();
        $sqlWhere = '';

        if($userData['type'] != 'Super Admin'){

             $stmtParams['branchId'] = base64_decode($userData['branchId']);   
        }

        if($date){
            $sqlWhere.= ' AND cmr.`billing_date` BETWEEN "' .date("Y-m-01",strtotime(str_replace('-', '/', $date))) . ' 00:00:00" AND "'.date("Y-m-t",strtotime(str_replace('-', '/', $date))) . ' 23:59:59"';    
        }
        if($purok &&  $purok != 'Y' ){
            $sqlWhere.= ' AND p.`id` = :purok';
            $stmtParams['purok'] = $purok;   
        }

        $query = $this->getEntityManager()->getConnection()->prepare("
            SELECT 
                CONCAT(c.`first_name`, ' ', c.`last_name`, ' - ', cm.`account_serial_no`) AS account,
                p.`description` AS purok,
                cmr.`billed_amount` AS billedAmount,
                cmr.`consume` AS consume
            FROM `client_account_billing` cmr
            LEFT JOIN `client_account` cm ON cm.`id` = cmr.`client_account_id` 
            LEFT JOIN `client` c ON c.`id` = cm.`client_id` 
            LEFT JOIN `purok` p ON p.`id` = cm.`purok_id` 
            WHERE cmr.`is_deleted` = 0 
            AND c.branch_id = :branchId 
            $sqlWhere 
            ORDER BY p.`description` ASC
        ");

        foreach($stmtParams as $k => $v){
            $query->bindValue($k, $v);

        }
       
        $res = $query->executeQuery();
        $result = $res->fetchAllAssociative();
        return $result;
   }

   public function get_pending_payment(){

        $query = $this->getEntityManager()->getConnection()->prepare("
                SELECT 
                    CONCAT(c.`first_name`, ' ', c.`last_name`) AS fullName,
                    b.`id` AS branchId,
                    cm.`account_serial_no` AS serialNo,
                    cmr.previousBilling AS previousBilling,
                    cmr.presentBilling AS presentBilling,
                    cmr.consume AS consume, 
                    DATE_FORMAT(cmr.billingDate, '%m/%d/%Y') AS billingDate,
                    DATE_FORMAT(cmr.dueDate, '%m/%d/%Y') AS dueDate,
                    cm.`remaining_balance` AS remainingBalance,
                    cmr.billedAmt AS billedAmount,
                    (cm.`remaining_balance` +  cmr.billedAmt ) AS totalBalance,
                    cmr.amountPerCubic AS amountPerCubic,
                    cm.`id`,
                    co.`description` AS company,
                    co.`id` AS companyId,
                    co.`address` AS companyAddress,
                    p.`description` AS purok,
                    c.`contact_no` AS contactNo,
                    DATE_FORMAT(cmc.firstPendingPayment, '%m/%d/%Y') AS firstPendingPayment  
                FROM `client_account` cm 
                LEFT JOIN `client` c ON c.`id` = cm.`client_id` 
                LEFT JOIN `purok` p ON p.`id` = cm.`purok_id` 
                LEFT JOIN `branch` b ON b.`id` = c.`branch_id`
                LEFT JOIN `company` co ON co.`id` = b.`company_id` 
                LEFT JOIN ( 
                    SELECT 
                        cmr.`status` AS status,
                        cmr.`previous_billing` AS previousBilling,
                        cmr.`present_billing` AS presentBilling,
                        cmr.`consume` AS consume,
                        cmr.`billing_date` AS billingDate,
                        cmr.`due_date` AS dueDate,
                        cmr.`billed_amount` AS billedAmt,
                        cmr.`amount_per_cubic` AS amountPerCubic,
                        cmr.`id` AS cmrId, cmr.`client_account_id` AS clientAccountId 
                    FROM `client_account_billing` cmr 
                    WHERE cmr.`status` = 'Pending Payment' 
                    AND cmr.`billing_date` IN ( 
                        SELECT 
                            MAX(billing_date) 
                            FROM `client_account_billing` s 
                        WHERE s.`status` = 'Pending Payment' 
                        AND s.`is_deleted` = 0 
                        GROUP BY s.`client_account_id` ) 
                    AND cmr.`is_deleted` = 0 
                    GROUP BY cmr.`client_account_id` ) cmr ON cm.`id` = cmr.clientAccountId 
                LEFT JOIN ( 
                    SELECT 
                        cmc.`due_date` AS firstPendingPayment,
                        cmc.`client_account_id` AS cclientAccountId 
                    FROM `client_account_billing` cmc 
                    WHERE cmc.`status` = 'Pending Payment' 
                    AND cmc.`billing_date` IN ( 
                        SELECT 
                            MIN(billing_date) 
                            FROM `client_account_billing` s 
                        WHERE s.`status` = 'Pending Payment' 
                        AND s.`is_deleted` = 0 
                        GROUP BY s.`client_account_id` ) 
                    AND cmc.`is_deleted` = 0 
                    GROUP BY cmc.`client_account_id` ) cmc ON cm.`id` = cmc.cclientAccountId   
                WHERE cm.`is_deleted` = 0 
                AND cm.`status` = 'Active' 
                AND cmr.cmrId IS NOT NULL 
                AND c.`is_deleted` = 0
                AND  cmr.dueDate <= DATE(NOW() - INTERVAL 3 DAY) 

            
        ");
       
        $res = $query->executeQuery();
        $result = $res->fetchAllAssociative();
        return $result;

    }

    public function monthBill($id){
        
        $lastDayOfMonth =  date('t');
        $yearAndMonth = date('Y-m');
        $endDate  = $yearAndMonth . '-' . $lastDayOfMonth;
        $startDate =  $yearAndMonth .'-01';
        
        $query = $this->getEntityManager()->getConnection()->prepare("
                SELECT 
                    cab.`id`
                FROM `client_account_billing` cab
                WHERE cab.`billing_date`  BETWEEN '".$startDate." 00:00:00' AND '".$endDate." 23:59:59'
                AND cab.`is_deleted` != 1
                AND cab.`client_account_id` = '".$id."'
            
        ");
       
        $res = $query->executeQuery();
        $result = $res->fetchAllAssociative();
        return isset($result[0]) ? $result[0] : [];

    }

    public function billing_report($dateFrom, $dateTo, $status, $userData){
       
        $stmtParams = array();
        $andWhere = ' ';

        if($userData['type'] != 'Super Admin'){
             $stmtParams['branchId'] = base64_decode($userData['branchId']);   
        }


    
       if($dateFrom != 'NULL' && $dateTo != 'NULL'){
            $andWhere .= ' AND cmb.`billing_date` BETWEEN "' . date('Y-m-d', strtotime(str_replace('-', '/', $dateFrom))) . ' 00:00:00" AND "' .  date('Y-m-d', strtotime(str_replace('-', '/', $dateTo))) . ' 23:59:59"';   
       } else if( $dateFrom != 'NULL'){
            $andWhere .= ' AND cmb.`billing_date` >= "' . date('Y-m-d', strtotime(str_replace('-', '/', $dateFrom))) . ' 00:00:00"';
       } else if($dateTo != 'NULL') {
            $andWhere .= ' AND cmb.`billing_date` <= "' .   date('Y-m-d', strtotime(str_replace('-', '/', $dateTo))) . ' 23:59:59"';
       }

       if($status && $status != 'All'){
            $andWhere .= ' AND cmb.`status` = :status';
            $stmtParams['status'] = $status;  
        }

        $query = $this->getEntityManager()->getConnection()->prepare("
                SELECT 
                
                    CONCAT(c.`first_name`, ' ', c.`last_name`) AS fullName,
                    cm.`description` AS accountName,
                    cmb.`status` AS status,
                    cm.`remarks` AS remarks,
                    cmb.`billed_amount` AS billingAmount,
                    DATE_FORMAT(cmb.`billing_date`, '%m/%d/%Y') AS billingDate
                FROM `client_account_billing` cmb 
                LEFT JOIN `client_account` cm ON cm.`id` = cmb.`client_account_id` 
                LEFT JOIN `client` c ON c.`id` = cm.`client_id` 
                LEFT JOIN `branch` b ON b.`id` = c.`branch_id`
                LEFT JOIN `company` co ON co.`id` = b.`company_id`   
                WHERE cmb.`is_deleted` = 0 
                AND c.`branch_id` = :branchId 
                AND c.`is_deleted` = 0
                AND cm.`is_deleted` = 0
                AND cm.`status` = 'Active'
                ".$andWhere."
                ORDER BY cmb.`billing_date` asc
        ");

        foreach($stmtParams as $k => $v){
            $query->bindValue($k, $v);

        }
       
        $res = $query->executeQuery();
        $result = $res->fetchAllAssociative();
        return $result;

    }

    

   
}
